version: "3.5"
services:
  sample-www:
    build:
      context: .docker/www
      dockerfile: Dockerfile
      args:
        SITE_URL: ${SITE_URL}
    container_name: sample-www
    ports:
      - "${WWW_HTTP_PORT}:80"
      - "${WWW_HTTPS_PORT}:443"
      - 8983:8983
    volumes:
      - sample-nfsmount:/var/www/html
    networks:
      - sample
  sample-mysql:
    image: mysql:5.7.31
    container_name: sample-mysql
    ports:
      - "${SS_DATABASE_LOCAL_PORT}:3306"
    volumes:
      - sample-mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SS_DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${SS_DATABASE_NAME}
      - MYSQL_USER=${SS_DATABASE_USERNAME}
      - MYSQL_PASSWORD=${SS_DATABASE_PASSWORD}
      - TZ=${TZ}
    networks:
      - sample
  sample-mailhog:
    image: mailhog/mailhog:latest
    container_name: sample-mailhog
    ports:
      - "${DEV_MAILER_PORT}:8025"
      - "1025:1025"
    networks:
      - sample
  sample-elasticsearch:
    image: elasticsearch:7.12.0
    container_name: sample-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - sample-esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - node.name=es03
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - sample
  sample-enterprisesearch:
    image: 'docker.elastic.co/enterprise-search/enterprise-search:7.12.0'
    container_name: sample-enterprisesearch
    ports:
        - '3002:3002'
    depends_on:
      - "sample-elasticsearch"
    environment:
        - 'elasticsearch.host=http://sample-elasticsearch:9200'
        - elasticsearch.username=elastic
        - elasticsearch.password=changeme
        - allow_es_settings_modification=true
        - 'secret_management.encryption_keys=[cf9047dcdbbf41ed5cbf448e300c68f6ca1ce92ec81e605e9aa4b8212d6e1456]'
    network_mode: sample_sample


networks:
  sample:
    driver: "bridge"

volumes:
  sample-mysqldata:
    driver: "local"
  sample-esdata:
    driver: "local"
